"""Type stubs for gitlab.v4.objects to fix type checking.

These classes all inherit from RESTObject at runtime, but type checkers
don't always recognize this due to python-gitlab's TypeVar usage.
"""

from gitlab.base import RESTObject

# All these classes inherit from RESTObject at runtime
class Project(RESTObject): ...
class ProjectBranch(RESTObject): ...
class ProjectCommit(RESTObject): ...
class ProjectIssue(RESTObject): ...
class ProjectIssueNote(RESTObject): ...
class ProjectLabel(RESTObject): ...
class ProjectMergeRequest(RESTObject): ...
class ProjectMergeRequestDiscussion(RESTObject): ...
class ProjectMergeRequestDiscussionNote(RESTObject): ...
class ProjectMergeRequestNote(RESTObject): ...
class ProjectMilestone(RESTObject): ...
class ProjectPipeline(RESTObject): ...
class ProjectPipelineJob(RESTObject): ...
class ProjectRelease(RESTObject): ...
class ProjectWiki(RESTObject): ...
class ProjectWikiPage(RESTObject): ...
